name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild (x64)
      id: setup_msbuild_path
      uses: ./
      with:
        vs-prerelease: true
        msbuild-architecture: 'x64'

    - name: echo MSBuild
      run: msbuild Capsicum.sln -property:Configuration=Release 
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: VSIX Publisher
      uses: cezarypiatek/VsixPublisherAction@0.2
      with:
        # The path to VSIX file
        extension-file: Capsicum\Capsicum\Capsicum.Vsix\bin\Release\net472\Capsicum.Vsix
        # The path to publish manifest file
        publish-manifest-file: Capsicum/publishManifest.json
        # The publisher access token
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
