name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  version: '2.2.${{ github.run_number }}'
  repoUrl: ${{ github.server_url }}/${{ github.repository }}
  Configuration: Release
  SolutionPath: Capsicum.sln
  
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2   

      - name: Update Assembly Version
        uses: dannevesdantas/set-version-assemblyinfo@v.1.0.0
        with:
          version: ${{ env.version }}

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: NuGet restore
        run: nuget restore $env:SolutionPath

      - name: Build VSIX
        run: msbuild $env:SolutionPath /t:Rebuild /p:Configuration=$env:Configuration
        env: 
          DeployExtension: False

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Capsicum
          path: |
            **\*.vsix
            publishManifest.json
            overview.md
  release:
    name: Release
    needs: build
    runs-on: windows-latest
    environment: Release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
          
      - name: Publish to Marketplace - VS2022
        uses: cezarypiatek/VsixPublisherAction@0.1
        with:
          extension-file: Capsicum\Capsicum\Capsicum\Capsicum.Vsix\bin\Release\net472\Capsicum.Vsix.vsix
          publish-manifest-file: SCapsicum/publishManifest.json
          personal-access-code: ${{ secrets.VISUALSTUDIO_PUBLISHER_ACCESS_TOKEN }}
